#import "ReactNativeModule.h"
#import <React/RCTBridgeModule.h>

// Import the Kotlin framework header (auto-generated by Kotlin Native)
#import <shared/Greeting.h>

@implementation ReactNativeModule

RCT_EXPORT_MODULE();

RCT_EXPORT_METHOD(getGreeting:(RCTPromiseResolveBlock)resolve
        rejecter:(RCTPromiseRejectBlock)reject)
{
    Greeting *greeting = [[Greeting alloc] init];
    NSString *message = [greeting greet]; // Assuming `greet()` is a method in your Kotlin class
    resolve(message);
}

@end
